export const memeFactoryAbi = [
  {
    type: "constructor",
    stateMutability: "nonpayable",
    inputs: [
      { name: "_olas", type: "address" },
      { name: "_nativeToken", type: "address" },
      { name: "_uniV3PositionManager", type: "address" },
      { name: "_buyBackBurner", type: "address" },
      { name: "_minNativeTokenValue", type: "uint256" },
      { name: "accounts", type: "address[]" },
      { name: "amounts", type: "uint256[]" },
    ],
  },
  {
    type: "event",
    name: "Collected",
    inputs: [
      { indexed: true, name: "hearter", type: "address" },
      { indexed: true, name: "memeToken", type: "address" },
      { indexed: false, name: "allocation", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "FeesCollected",
    inputs: [
      { indexed: true, name: "feeCollector", type: "address" },
      { indexed: true, name: "memeToken", type: "address" },
      { indexed: false, name: "nativeTokenAmount", type: "uint256" },
      { indexed: false, name: "memeTokenAmount", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "Hearted",
    inputs: [
      { indexed: true, name: "hearter", type: "address" },
      { indexed: true, name: "memeNonce", type: "uint256" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "OLASJourneyToAscendance",
    inputs: [{ indexed: false, name: "amount", type: "uint256" }],
  },
  {
    type: "event",
    name: "Purged",
    inputs: [
      { indexed: true, name: "memeToken", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "Summoned",
    inputs: [
      { indexed: true, name: "summoner", type: "address" },
      { indexed: true, name: "memeNonce", type: "uint256" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "Unleashed",
    inputs: [
      { indexed: true, name: "unleasher", type: "address" },
      { indexed: true, name: "memeNonce", type: "uint256" },
      { indexed: true, name: "memeToken", type: "address" },
      { indexed: false, name: "lpTokenId", type: "uint256" },
      { indexed: false, name: "liquidity", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "COLLECT_DELAY",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "CONTRIBUTION_AGNT",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "DECIMALS",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint8" }],
  },
  {
    type: "function",
    name: "FEE_TIER",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint24" }],
  },
  {
    type: "function",
    name: "LIQUIDITY_AGNT",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "LP_PERCENTAGE",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "MAX_TICK",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "int24" }],
  },
  {
    type: "function",
    name: "MIN_TICK",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "int24" }],
  },
  {
    type: "function",
    name: "MIN_TOTAL_SUPPLY",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "OLAS_BURN_PERCENTAGE",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "SUMMON_AGNT",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "UNLEASH_DELAY",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "VERSION",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "string" }],
  },
  {
    type: "function",
    name: "buyBackBurner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "collectFees",
    stateMutability: "nonpayable",
    inputs: [{ name: "tokens", type: "address[]" }],
    outputs: [],
  },
  {
    type: "function",
    name: "collectThisMeme",
    stateMutability: "nonpayable",
    inputs: [{ name: "memeToken", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "heartThisMeme",
    stateMutability: "payable",
    inputs: [{ name: "memeNonce", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "launchCampaignNonce",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "mapAccountActivities",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "memeHearters",
    stateMutability: "view",
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "address" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "memeSummons",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { type: "string", name: "name" },
      { type: "string", name: "symbol" },
      { type: "uint256", name: "totalSupply" },
      { type: "uint256", name: "nativeTokenContributed" },
      { type: "uint256", name: "summonTime" },
      { type: "uint256", name: "unleashTime" },
      { type: "uint256", name: "heartersAmount" },
      { type: "uint256", name: "positionId" },
      { type: "bool", name: "isNativeFirst" },
    ],
  },
  {
    type: "function",
    name: "memeTokenNonces",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "memeTokens",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "minNativeTokenValue",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "nativeToken",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "numTokens",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "olas",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "purgeThisMeme",
    stateMutability: "nonpayable",
    inputs: [{ name: "memeToken", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "scheduleForAscendance",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "scheduledForAscendance",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "summonThisMeme",
    stateMutability: "payable",
    inputs: [
      { name: "name", type: "string" },
      { name: "symbol", type: "string" },
      { name: "totalSupply", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "uniV3PositionManager",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "unleashThisMeme",
    stateMutability: "nonpayable",
    inputs: [{ name: "memeNonce", type: "uint256" }],
    outputs: [],
  },
] as const;
