export const FSM_CONFIG = {
  alphabetIn: [
    "DONE",
    "ERROR",
    "NO_FUNDS",
    "NO_MAJORITY",
    "ROUND_TIMEOUT",
    "SETTLE",
    "WAIT",
  ],
  defaultStartState: "LoadDatabaseRound",
  finalStates: ["FinishedToResetRound", "FinishedToSettlementRound"],
  startStates: [
    "ActionPreparationRound",
    "LoadDatabaseRound",
    "PullMemesRound",
  ],
  states: [
    "ActionDecisionRound",
    "ActionPreparationRound",
    "ActionTweetRound",
    "CheckFundsRound",
    "CollectFeedbackRound",
    "EngageTwitterRound",
    "FinishedToResetRound",
    "FinishedToSettlementRound",
    "LoadDatabaseRound",
    "PullMemesRound",
  ],
  transitionFunc: {
    ActionDecisionRound: {
      DONE: "ActionPreparationRound",
      NO_MAJORITY: "ActionDecisionRound",
      ROUND_TIMEOUT: "ActionDecisionRound",
      WAIT: "FinishedToResetRound",
    },
    ActionPreparationRound: {
      DONE: "ActionTweetRound",
      ERROR: "FinishedToResetRound",
      NO_MAJORITY: "ActionPreparationRound",
      ROUND_TIMEOUT: "ActionPreparationRound",
      SETTLE: "CheckFundsRound",
    },
    ActionTweetRound: {
      DONE: "FinishedToResetRound",
      ERROR: "ActionTweetRound",
      NO_MAJORITY: "ActionTweetRound",
      ROUND_TIMEOUT: "ActionTweetRound",
    },
    CheckFundsRound: {
      DONE: "FinishedToSettlementRound",
      NO_FUNDS: "CheckFundsRound",
      NO_MAJORITY: "CheckFundsRound",
      ROUND_TIMEOUT: "CheckFundsRound",
    },
    CollectFeedbackRound: {
      DONE: "EngageTwitterRound",
      ERROR: "CollectFeedbackRound",
      NO_MAJORITY: "CollectFeedbackRound",
      ROUND_TIMEOUT: "CollectFeedbackRound",
    },
    EngageTwitterRound: {
      DONE: "ActionDecisionRound",
      ERROR: "EngageTwitterRound",
      NO_MAJORITY: "EngageTwitterRound",
      ROUND_TIMEOUT: "EngageTwitterRound",
    },
    LoadDatabaseRound: {
      DONE: "PullMemesRound",
      NO_MAJORITY: "LoadDatabaseRound",
      ROUND_TIMEOUT: "LoadDatabaseRound",
    },
    PullMemesRound: {
      DONE: "CollectFeedbackRound",
      NO_MAJORITY: "PullMemesRound",
      ROUND_TIMEOUT: "PullMemesRound",
    },
  },
};
